import random

mushroomList = [
    "Agaricus bisporus",
    "Oyster Mushroom",
    "Chanterelle",
    "Flammulina filiformis",
    "Hen-of-the-wood",
    "Shiitake",
    "Penny Bun",
    "Lion's mane",
    "Hydnum repandum",
    "Chicken of the woods",
    "Clitocybe nuda",
    "Craterellus cornucopioides",
    "Death cap",
    "King trumpet mushroom",
    "Fly agaric",
    "Matsutake",
    "Turkey tail",
    "Giant puffball",
    "Dryad's saddle",
    "Yellow morel",
    "Lactarius deliciosus",
    "Lobster mushroom",
    "Agaricus campestris",
    "Sparassis crispa",
    "Parasol mushroom",
    "Reishi mushroom",
    "Wood ear",
    "Shaggy mane",
    "Stropharia rugosoannulata",
    "Lingzhi",
    "Honey fungus",
    "Gyromitra esculenta",
    "Magic mushrooms",
    "Cortinarius caperatus",
    "Russula xerampelina",
    "Pleutorus citrinopileatus",
    "Straw mushroom",
    "Indigo milk cap",
    "Suillus luteus",
    "Liberty cap",
    "Morchella americana",
    "Morchella angusticeps",
    "Russula cyanoxantha",
    "Morchella elata",
    "Corn smut",
    "Pleurotus pulmonarius",
    "Birch polypore",
    "Shimeji mushroom",
    "Pholiota microspora",
    "Blusher",
    "Cyclocybe aegerita",
    "Amanita albocreata",
    "Amanita aliena",
    "Amanita altipes",
    "Amanita aprica",
    "Amanita armeniaca",
    "Amanita augusta",
    "Amanita breckonii",
    "Amanita chrysoblema",
    "Amanita eliae",
    "Amanita farinosa",
    "Amanita frostiana",
    "Amanita gemmata",
    "Amanita multisquamosa",
    "Amanita nehuta",
    "Amanita parcivolvata",
    "Amanita pantherina",
    "Amanita persicina",
    "Judas' ear",
    "Butter bolete",
    "Bay bolete",
    "Barrow\'s bolete",
    "Two-colored bolete",
    "King bolete",
    "Sweetbread mushroom",
    "Alcohol inky cap",
    "Mica cap",
    "Bracelet cortinartius",
    "Pig's ear",
    "Snowbank false morel",
    "Coral hericium",
    "Bear's head",
    "Comb tooth mushroom",
    "Hedgehog mushroom",
    "Orange-capped scaber stalk",
    "Aspen scaber stalk",
    "Manzanita scaber stalk",
    "Green-spored parasol",
    "Blewit",
    "Fairy-ring mushroom",
    "Old man of the woods",
    "Painted suillus",
    "Black kame",
    "Brown kame",
    "Summer truffle",
    "Oregon white truffle",
    "Italian white truffle",
    "French black truffle",
    "Texas white truffle",
    "American abrupt-bulbed Lepidella",
    "Eastern destroying angel amanita",
    "Gymnopus fusipes"
]

def getMushroom():
    return mushroomList[random.randint(0,(len(mushroomList)-1))]